class PalavraForca {
  late String palavra;
  late String dica;

  PalavraForca(this.palavra, this.dica);
}

//PalavraForca listapalavras[];
List<PalavraForca> listapalavras = [];

void DefinirPalavras() {
  PalavraForca listPa1 = new PalavraForca('Maça', 'Fruta');
  listapalavras.add(listPa1);
  PalavraForca listPa2 = new PalavraForca('Rinoceronte', 'Animal');
  listapalavras.add(listPa2);
  PalavraForca listPa3 = new PalavraForca('Refrigerante', 'Bebida');
  listapalavras.add(listPa3);
  PalavraForca listPa4 = new PalavraForca('Velocidade', 'Física');
  listapalavras.add(listPa4);
  PalavraForca listPa5 = new PalavraForca('Ação', 'Gênero');
  listapalavras.add(listPa5);
  PalavraForca listPa6 = new PalavraForca('Sexualidade', 'Caracteristica');
  listapalavras.add(listPa6);
  PalavraForca listPa7 = new PalavraForca('Livro', 'Objeto');
  listapalavras.add(listPa7);
  PalavraForca listPa8 = new PalavraForca('Pandemia', 'Sáude');
  listapalavras.add(listPa8);
  PalavraForca listPa9 = new PalavraForca('Seriado', 'TV');
  listapalavras.add(listPa9);
  PalavraForca listPa10 = new PalavraForca('Televisão', 'Aparelho');
  listapalavras.add(listPa10);
  PalavraForca listPa11 = new PalavraForca('Amendoim', 'Alimento');
  listapalavras.add(listPa11);
  PalavraForca listPa12 = new PalavraForca('Mão', 'Humano');
  listapalavras.add(listPa12);
  PalavraForca listPa13 = new PalavraForca('Salvador', 'Cidade');
  listapalavras.add(listPa13);
  PalavraForca listPa14 = new PalavraForca('Hamburguer', 'Alimento');
  listapalavras.add(listPa14);
  PalavraForca listPa15 = new PalavraForca('Numeral', 'Matematica');
  listapalavras.add(listPa15);
  PalavraForca listPa16 = new PalavraForca('Matemática', 'Matéria Escolar');
  listapalavras.add(listPa16);
  PalavraForca listPa17 = new PalavraForca('Ostra', 'Mar');
  listapalavras.add(listPa17);
  PalavraForca listPa18 = new PalavraForca('Escola', 'Lugar');
  listapalavras.add(listPa18);
  PalavraForca listPa19 = new PalavraForca('Lésbica', 'Caracteristica');
  listapalavras.add(listPa19);
  PalavraForca listPa20 = new PalavraForca('Pedra', 'Natureza');
  listapalavras.add(listPa20);
  PalavraForca listPa21 = new PalavraForca('Complexidade', 'Caracteristica');
  listapalavras.add(listPa21);
  PalavraForca listPa22 = new PalavraForca('Ciência', 'Materia Escolar');
  listapalavras.add(listPa22);
  PalavraForca listPa23 = new PalavraForca('Psicologia', 'Ciência');
  listapalavras.add(listPa23);
  PalavraForca listPa24 = new PalavraForca('Copo', 'Objeto');
  listapalavras.add(listPa24);
  PalavraForca listPa25 = new PalavraForca('Zero', 'Numero');
  listapalavras.add(listPa25);
  PalavraForca listPa26 = new PalavraForca('Cidade', 'Lugar');
  listapalavras.add(listPa26);
  PalavraForca listPa27 = new PalavraForca('Strogonoff', 'Alimento');
  listapalavras.add(listPa27);
  PalavraForca listPa28 = new PalavraForca('Musico', 'Profissão');
  listapalavras.add(listPa28);
  PalavraForca listPa29 = new PalavraForca('Política', 'Filosofia');
  listapalavras.add(listPa29);
  PalavraForca listPa30 = new PalavraForca('Filosofia', 'Materia Escolar');
  listapalavras.add(listPa30);
  PalavraForca listPa31 = new PalavraForca('Herói', 'Cultura Pop');
  listapalavras.add(listPa31);
  PalavraForca listPa32 = new PalavraForca('Vilão', 'Cultura Pop');
  listapalavras.add(listPa32);
  PalavraForca listPa33 = new PalavraForca('Ribeirão Preto', 'Cidade');
  listapalavras.add(listPa33);
  PalavraForca listPa34 = new PalavraForca('Novidade', 'Coisa Nova');
  listapalavras.add(listPa34);
  PalavraForca listPa35 = new PalavraForca('Tartaruga', 'Animal');
  listapalavras.add(listPa35);
  PalavraForca listPa36 = new PalavraForca('Força', 'Caracteristica');
  listapalavras.add(listPa36);
  PalavraForca listPa37 = new PalavraForca('Invasão', 'Guerra');
  listapalavras.add(listPa37);
  PalavraForca listPa38 = new PalavraForca('Papel Higiênico', 'Higiêne');
  listapalavras.add(listPa38);
  PalavraForca listPa39 = new PalavraForca('Eternidade', 'Tempo');
  listapalavras.add(listPa39);
  PalavraForca listPa40 = new PalavraForca('Corretor', 'Profissão');
  listapalavras.add(listPa40);
  PalavraForca listPa41 = new PalavraForca('Aniversário', 'Data');
  listapalavras.add(listPa41);
  PalavraForca listPa42 = new PalavraForca('Sexo', 'Relações');
  listapalavras.add(listPa42);
  PalavraForca listPa43 = new PalavraForca('Versátil', 'Caracteristica');
  listapalavras.add(listPa43);
  PalavraForca listPa44 = new PalavraForca('Tecnologia', 'Conceito');
  listapalavras.add(listPa44);
  PalavraForca listPa45 = new PalavraForca('Corrida', 'Exercício');
  listapalavras.add(listPa45);
  PalavraForca listPa46 = new PalavraForca('Garrafa', 'Objeto');
  listapalavras.add(listPa46);
  PalavraForca listPa47 = new PalavraForca('Gasolina', 'Veículos');
  listapalavras.add(listPa47);
  PalavraForca listPa48 = new PalavraForca('Fantasma', 'Criaturas');
  listapalavras.add(listPa48);
  PalavraForca listPa49 = new PalavraForca('Legado', 'Futuro');
  listapalavras.add(listPa49);
  PalavraForca listPa50 = new PalavraForca('Futuro', 'Tempo');
  listapalavras.add(listPa50);
  PalavraForca listPa51 = new PalavraForca('Tempo', 'Data');
  listapalavras.add(listPa51);
  PalavraForca listPa52 = new PalavraForca('Chuveiro', 'Objeto');
  listapalavras.add(listPa52);
  PalavraForca listPa53 = new PalavraForca('Pé', 'Humano');
  listapalavras.add(listPa53);
  PalavraForca listPa54 = new PalavraForca('Poção', 'Bruxaria');
  listapalavras.add(listPa54);
  PalavraForca listPa55 = new PalavraForca('Latitude', 'Geografia');
  listapalavras.add(listPa55);
  PalavraForca listPa56 = new PalavraForca('Longitude', 'Geografia');
  listapalavras.add(listPa56);
  PalavraForca listPa57 = new PalavraForca('Maior', 'Intensidade');
  listapalavras.add(listPa57);
  PalavraForca listPa58 = new PalavraForca('Menor', 'Intensidade');
  listapalavras.add(listPa58);
  PalavraForca listPa59 = new PalavraForca('Intensidade', 'Conceito');
  listapalavras.add(listPa59);
  PalavraForca listPa60 = new PalavraForca('Farinha', 'Alimento');
  listapalavras.add(listPa60);
  PalavraForca listPa61 = new PalavraForca('Monstro', 'Criatura');
  listapalavras.add(listPa61);
  PalavraForca listPa62 = new PalavraForca('Mitologia', 'Conceito');
  listapalavras.add(listPa62);
  PalavraForca listPa63 = new PalavraForca('Embalagem', 'Propaganda');
  listapalavras.add(listPa63);
  PalavraForca listPa64 = new PalavraForca('Pão de Queijo', 'Comida');
  listapalavras.add(listPa64);
  PalavraForca listPa65 = new PalavraForca('Casal', 'Amor');
  listapalavras.add(listPa65);
  PalavraForca listPa66 = new PalavraForca('Cão', 'Animal');
  listapalavras.add(listPa66);
  PalavraForca listPa67 = new PalavraForca('Fim', 'Tempo');
  listapalavras.add(listPa67);
  PalavraForca listPa68 = new PalavraForca('Campeonato', 'Competição');
  listapalavras.add(listPa68);
  PalavraForca listPa69 = new PalavraForca('Sangue', 'Humano');
  listapalavras.add(listPa69);
  PalavraForca listPa70 = new PalavraForca('Mar', 'Água');
  listapalavras.add(listPa70);
  PalavraForca listPa71 = new PalavraForca('Difícil', 'Intensidade');
  listapalavras.add(listPa71);
  PalavraForca listPa72 = new PalavraForca('Muito', 'Intensidade');
  listapalavras.add(listPa72);
  PalavraForca listPa73 = new PalavraForca('Raio', 'Natureza');
  listapalavras.add(listPa73);
  PalavraForca listPa74 = new PalavraForca('Eletricidade', 'Física');
  listapalavras.add(listPa74);
  PalavraForca listPa75 = new PalavraForca('Força', 'Intensidade');
  listapalavras.add(listPa75);
  PalavraForca listPa76 = new PalavraForca('Caminho', 'GPS');
  listapalavras.add(listPa76);
  PalavraForca listPa77 = new PalavraForca('Ir', 'Verbo');
  listapalavras.add(listPa77);
  PalavraForca listPa78 = new PalavraForca('Viver', 'Verbo');
  listapalavras.add(listPa78);
  PalavraForca listPa79 = new PalavraForca('Quebra Cabeça', 'Jogo');
  listapalavras.add(listPa79);
  PalavraForca listPa80 = new PalavraForca('Plataforma', 'Chão');
  listapalavras.add(listPa80);
  PalavraForca listPa81 = new PalavraForca('Chão', 'Lugar');
  listapalavras.add(listPa81);
  PalavraForca listPa82 = new PalavraForca('Princessa', 'Realeza');
  listapalavras.add(listPa82);
  PalavraForca listPa83 = new PalavraForca('Diamante', 'Mineral');
  listapalavras.add(listPa83);
  PalavraForca listPa84 = new PalavraForca('Mineral', 'Natureza');
  listapalavras.add(listPa84);
  PalavraForca listPa85 = new PalavraForca('Natureza', 'Planeta Terra');
  listapalavras.add(listPa85);
  PalavraForca listPa86 = new PalavraForca('Vida', 'Humano');
  listapalavras.add(listPa86);
  PalavraForca listPa87 = new PalavraForca('Xbox', 'Máquina');
  listapalavras.add(listPa87);
  PalavraForca listPa88 = new PalavraForca('Pagar', 'Verbo');
  listapalavras.add(listPa88);
  PalavraForca listPa89 = new PalavraForca('Princípe', 'Realeza');
  listapalavras.add(listPa89);
  PalavraForca listPa90 = new PalavraForca('Rua', 'Lugar');
  listapalavras.add(listPa90);
  PalavraForca listPa91 = new PalavraForca('Amizade', 'Laço entre pessoas');
  listapalavras.add(listPa91);
  PalavraForca listPa92 = new PalavraForca('Pouco', 'Intensidade');
  listapalavras.add(listPa92);
  PalavraForca listPa93 = new PalavraForca('Drogaria', 'Comércio');
  listapalavras.add(listPa93);
  PalavraForca listPa94 = new PalavraForca('Comércio', 'Tipo de troca');
  listapalavras.add(listPa94);
  PalavraForca listPa95 = new PalavraForca('Quadrinhos', 'Arte');
  listapalavras.add(listPa95);
  PalavraForca listPa96 = new PalavraForca('Vampiro', 'Criatura');
  listapalavras.add(listPa96);
  PalavraForca listPa97 = new PalavraForca('Caminhar', 'Intensidade');
  listapalavras.add(listPa97);
  PalavraForca listPa98 = new PalavraForca('Peregrino', 'Viajante');
  listapalavras.add(listPa98);
  PalavraForca listPa99 = new PalavraForca('Viajante', 'Pessoa');
  listapalavras.add(listPa99);
  PalavraForca listPa100 = new PalavraForca('Pessoa', 'Humano');
  listapalavras.add(listPa100);
  PalavraForca listPa101 = new PalavraForca('Fio', 'Objeto');
  listapalavras.add(listPa101);
  PalavraForca listPa102 = new PalavraForca('Sonho', 'Imaginação');
  listapalavras.add(listPa102);
  PalavraForca listPa103 = new PalavraForca('Imaginação', 'Conceito');
  listapalavras.add(listPa103);
  PalavraForca listPa104 = new PalavraForca('Futebol', 'Esporte');
  listapalavras.add(listPa104);
  PalavraForca listPa105 = new PalavraForca('Esporte', 'Exercicio');
  listapalavras.add(listPa105);
  PalavraForca listPa106 = new PalavraForca('Cego', 'Condição Humana');
  listapalavras.add(listPa106);
  PalavraForca listPa107 = new PalavraForca('Lobo', 'Animal');
  listapalavras.add(listPa107);
  PalavraForca listPa108 = new PalavraForca('Tigre', 'Animal');
  listapalavras.add(listPa108);
  PalavraForca listPa109 = new PalavraForca('Guitarra', 'Instrumento');
  listapalavras.add(listPa109);
  PalavraForca listPa110 = new PalavraForca('Instrumento', 'Objeto');
  listapalavras.add(listPa110);
  PalavraForca listPa111 = new PalavraForca('Melodia', 'Música');
  listapalavras.add(listPa111);
  PalavraForca listPa112 = new PalavraForca('Música', 'Arte');
  listapalavras.add(listPa112);
  PalavraForca listPa113 = new PalavraForca('Som', 'Se ouve');
  listapalavras.add(listPa113);
  PalavraForca listPa114 = new PalavraForca('Aranha', 'Animal');
  listapalavras.add(listPa114);
  PalavraForca listPa115 = new PalavraForca('Pescar', 'Verbo');
  listapalavras.add(listPa115);
  PalavraForca listPa116 = new PalavraForca('Amor', 'Sentimento');
  listapalavras.add(listPa116);
  PalavraForca listPa117 = new PalavraForca('Carro', 'Esporte');
  listapalavras.add(listPa117);
  PalavraForca listPa118 = new PalavraForca('Tudo', 'Conceito');
  listapalavras.add(listPa118);
  PalavraForca listPa119 = new PalavraForca('Churros', 'Alimento');
  listapalavras.add(listPa119);
  PalavraForca listPa120 = new PalavraForca('Tênis', 'Esporte/Objeto');
  listapalavras.add(listPa120);
  PalavraForca listPa121 = new PalavraForca('Sorvete', 'Alimento');
  listapalavras.add(listPa121);
  PalavraForca listPa122 = new PalavraForca('Noite', 'Tempo');
  listapalavras.add(listPa122);
  PalavraForca listPa123 = new PalavraForca('Dia', 'Tempo');
  listapalavras.add(listPa123);
  PalavraForca listPa124 = new PalavraForca('Biblioteca', 'Lugar');
  listapalavras.add(listPa124);
  PalavraForca listPa125 = new PalavraForca('Coração', 'Orgão');
  listapalavras.add(listPa125);
  PalavraForca listPa126 = new PalavraForca('Orgão', 'Corpo Humano');
  listapalavras.add(listPa126);
  PalavraForca listPa127 = new PalavraForca('Sempre', 'Tempo');
  listapalavras.add(listPa127);
  PalavraForca listPa128 = new PalavraForca('Bolo', 'Alimento');
  listapalavras.add(listPa128);
  PalavraForca listPa129 = new PalavraForca('Futebol', 'Esporte');
  listapalavras.add(listPa129);
  PalavraForca listPa130 = new PalavraForca('Poder', 'Conceito');
  listapalavras.add(listPa130);
  PalavraForca listPa131 = new PalavraForca('Família', 'Lar');
  listapalavras.add(listPa131);
  PalavraForca listPa132 = new PalavraForca('Lar', 'Casa');
  listapalavras.add(listPa132);
  PalavraForca listPa133 = new PalavraForca('Casa', 'Lugar');
  listapalavras.add(listPa133);
  PalavraForca listPa134 = new PalavraForca('Super', 'Intensidade');
  listapalavras.add(listPa134);
  PalavraForca listPa135 = new PalavraForca('Morcego', 'Animal');
  listapalavras.add(listPa135);
  PalavraForca listPa136 = new PalavraForca('Maravilha', 'Coisa ótima');
  listapalavras.add(listPa136);
  PalavraForca listPa137 = new PalavraForca('Velocidade', 'Física');
  listapalavras.add(listPa137);
  PalavraForca listPa138 = new PalavraForca('Lanterna', 'Objeto');
  listapalavras.add(listPa138);
  PalavraForca listPa139 = new PalavraForca('Água', 'Elemento');
  listapalavras.add(listPa139);
  PalavraForca listPa140 = new PalavraForca('Gavião', 'Animal');
  listapalavras.add(listPa140);
  PalavraForca listPa141 = new PalavraForca('Campeão', 'Vencedor');
  listapalavras.add(listPa141);
  PalavraForca listPa142 = new PalavraForca('Arqueiro', 'Alvo');
  listapalavras.add(listPa142);
  PalavraForca listPa143 = new PalavraForca('Canário', 'Animal');
  listapalavras.add(listPa143);
  PalavraForca listPa144 = new PalavraForca('Magia', 'Bruxaria');
  listapalavras.add(listPa144);
  PalavraForca listPa145 = new PalavraForca('Alienígena', 'Espaço');
  listapalavras.add(listPa145);
  PalavraForca listPa146 = new PalavraForca('África', 'Lugar');
  listapalavras.add(listPa146);
  PalavraForca listPa147 = new PalavraForca('Átomo', 'Física');
  listapalavras.add(listPa147);
  PalavraForca listPa148 = new PalavraForca('Nuclear', 'Tóxico');
  listapalavras.add(listPa148);
  PalavraForca listPa149 = new PalavraForca('Katana', 'Arma');
  listapalavras.add(listPa149);
  PalavraForca listPa150 = new PalavraForca('Metamorfose', 'Transformação');
  listapalavras.add(listPa150);
  PalavraForca listPa151 = new PalavraForca('Halo', 'Celestial');
  listapalavras.add(listPa151);
  PalavraForca listPa152 = new PalavraForca('Vibração', 'Tremores');
  listapalavras.add(listPa152);
  PalavraForca listPa153 = new PalavraForca('Asa', 'Animal');
  listapalavras.add(listPa153);
  PalavraForca listPa154 = new PalavraForca('Vermelho', 'Cor');
  listapalavras.add(listPa154);
  PalavraForca listPa155 = new PalavraForca('Amazona', 'Espécie');
  listapalavras.add(listPa155);
  PalavraForca listPa156 = new PalavraForca('Garota', 'Pessoa');
  listapalavras.add(listPa156);
  PalavraForca listPa157 = new PalavraForca('Rapaz', 'Pessoa');
  listapalavras.add(listPa157);
  PalavraForca listPa158 = new PalavraForca('Quadrado', 'Forma');
  listapalavras.add(listPa158);
  PalavraForca listPa159 = new PalavraForca('Alface', 'Alimento');
  listapalavras.add(listPa159);
  PalavraForca listPa160 = new PalavraForca('Janela', 'Casas');
  listapalavras.add(listPa160);
  PalavraForca listPa161 = new PalavraForca('Luz', 'Brilho');
  listapalavras.add(listPa161);
  PalavraForca listPa162 = new PalavraForca('Novo', 'Estado de um objeto');
  listapalavras.add(listPa162);
  PalavraForca listPa163 = new PalavraForca('Distância', 'Espaço');
  listapalavras.add(listPa163);
  PalavraForca listPa164 = new PalavraForca('Ar', 'Elemento');
  listapalavras.add(listPa164);
  PalavraForca listPa165 = new PalavraForca('Fogo', 'Elemento');
  listapalavras.add(listPa165);
  PalavraForca listPa166 = new PalavraForca('Gay', 'Caracteristica');
  listapalavras.add(listPa166);
  PalavraForca listPa167 = new PalavraForca('Transexual', 'Caracteristica');
  listapalavras.add(listPa167);
  PalavraForca listPa168 = new PalavraForca('Quebrar', 'Verbo');
  listapalavras.add(listPa168);
  PalavraForca listPa169 = new PalavraForca('Laser', 'Tipo de luz');
  listapalavras.add(listPa169);
  PalavraForca listPa170 = new PalavraForca('Sozinho', 'Caracteristica');
  listapalavras.add(listPa170);
  PalavraForca listPa171 = new PalavraForca('Desenho Animado', 'Infância');
  listapalavras.add(listPa171);
  PalavraForca listPa172 = new PalavraForca('Infância', 'Época');
  listapalavras.add(listPa172);
  PalavraForca listPa173 = new PalavraForca('Criança', 'Pessoa');
  listapalavras.add(listPa173);
  PalavraForca listPa174 = new PalavraForca('Sofá', 'Movél');
  listapalavras.add(listPa174);
  PalavraForca listPa175 = new PalavraForca('Ilha Bela', 'Lugar');
  listapalavras.add(listPa175);
  PalavraForca listPa176 = new PalavraForca('Fôlego', 'Respiração');
  listapalavras.add(listPa176);
  PalavraForca listPa177 = new PalavraForca('Respiração', 'Expirar');
  listapalavras.add(listPa177);
  PalavraForca listPa178 = new PalavraForca('Um', 'Numeral');
  listapalavras.add(listPa178);
  PalavraForca listPa179 = new PalavraForca('Animação', 'Estilo de filme');
  listapalavras.add(listPa179);
  PalavraForca listPa180 = new PalavraForca('Erva Danilha', 'Natureza');
  listapalavras.add(listPa180);
  PalavraForca listPa181 = new PalavraForca('Vulcão', 'Natureza');
  listapalavras.add(listPa181);
  PalavraForca listPa182 = new PalavraForca('Medicina', 'Profissão');
  listapalavras.add(listPa182);
  PalavraForca listPa183 =
      new PalavraForca('Profissão', 'Trabalho com salário');
  listapalavras.add(listPa183);
  PalavraForca listPa184 = new PalavraForca('Com', 'Gramática');
  listapalavras.add(listPa184);
  PalavraForca listPa185 = new PalavraForca('Leitura', 'Atividade');
  listapalavras.add(listPa185);
  PalavraForca listPa186 = new PalavraForca('Ser', 'Vivo');
  listapalavras.add(listPa186);
  PalavraForca listPa187 = new PalavraForca('Você', 'Pronome');
  listapalavras.add(listPa187);
  PalavraForca listPa188 = new PalavraForca('Pronome', 'Gramática');
  listapalavras.add(listPa188);
  PalavraForca listPa189 = new PalavraForca('Gramática', 'Materia Escolar');
  listapalavras.add(listPa189);
  PalavraForca listPa190 = new PalavraForca('Português', 'Materia Escolar');
  listapalavras.add(listPa190);
  PalavraForca listPa191 = new PalavraForca('Beijo', 'Amor');
  listapalavras.add(listPa191);
  PalavraForca listPa192 =
      new PalavraForca('Educação Fisíca', 'Materia Escolar');
  listapalavras.add(listPa192);
  PalavraForca listPa193 = new PalavraForca('Coisa', 'Objeto');
  listapalavras.add(listPa193);
  PalavraForca listPa194 = new PalavraForca('Quarteto', '4');
  listapalavras.add(listPa194);
  PalavraForca listPa195 = new PalavraForca('Casamento', 'Amor');
  listapalavras.add(listPa195);
  PalavraForca listPa196 = new PalavraForca('Doce', 'Alimento');
  listapalavras.add(listPa196);
  PalavraForca listPa197 = new PalavraForca('Alimento', 'Comida');
  listapalavras.add(listPa197);
  PalavraForca listPa198 = new PalavraForca('Comida', 'Alimento');
  listapalavras.add(listPa198);
  PalavraForca listPa199 = new PalavraForca('Imobiliária', 'Comércio');
  listapalavras.add(listPa199);
  PalavraForca listPa200 = new PalavraForca('Verde', 'Cor');
  listapalavras.add(listPa200);
  PalavraForca listPa201 = new PalavraForca('Caneta', 'Objeto');
  listapalavras.add(listPa201);
  PalavraForca listPa202 = new PalavraForca('Azul', 'Cor');
  listapalavras.add(listPa202);
  PalavraForca listPa203 = new PalavraForca('Amarelo', 'Cor');
  listapalavras.add(listPa203);
  PalavraForca listPa204 = new PalavraForca('Quebrar', 'Verbo');
  listapalavras.add(listPa204);
  PalavraForca listPa205 = new PalavraForca('Nome', 'Caracteristica');
  listapalavras.add(listPa205);
  PalavraForca listPa206 = new PalavraForca('Fã', 'Pessoa');
  listapalavras.add(listPa206);
  PalavraForca listPa207 = new PalavraForca('Gota', 'Água');
  listapalavras.add(listPa207);
  PalavraForca listPa208 = new PalavraForca('Entre', 'Advérbio');
  listapalavras.add(listPa208);
  PalavraForca listPa209 = new PalavraForca('Chuva', 'Clima');
  listapalavras.add(listPa209);
  PalavraForca listPa210 = new PalavraForca('Livre', 'Caracteristica');
  listapalavras.add(listPa210);
  PalavraForca listPa211 = new PalavraForca('Tridente', 'Arma');
  listapalavras.add(listPa211);
  PalavraForca listPa212 = new PalavraForca('Palavra', 'Gramática');
  listapalavras.add(listPa212);
  PalavraForca listPa213 = new PalavraForca('Supermercado', 'Lugar');
  listapalavras.add(listPa213);
  PalavraForca listPa214 = new PalavraForca('Mercado', 'Lugar');
  listapalavras.add(listPa214);
  PalavraForca listPa215 = new PalavraForca('Avenida', 'Lugar');
  listapalavras.add(listPa215);
  PalavraForca listPa216 = new PalavraForca('Faculdade', 'Lugar');
  listapalavras.add(listPa216);
  PalavraForca listPa217 = new PalavraForca('Universidade', 'Lugar');
  listapalavras.add(listPa217);
  PalavraForca listPa218 = new PalavraForca('Continente', 'Lugar');
  listapalavras.add(listPa218);
  PalavraForca listPa219 = new PalavraForca('Apartamento', 'Lugar');
  listapalavras.add(listPa219);
  PalavraForca listPa220 = new PalavraForca('Kitnet', 'Lugar');
  listapalavras.add(listPa220);
  PalavraForca listPa221 = new PalavraForca('Cantina', 'Lugar');
  listapalavras.add(listPa221);
  PalavraForca listPa222 = new PalavraForca('Campo', 'Lugar');
  listapalavras.add(listPa222);
  PalavraForca listPa223 = new PalavraForca('Mansão', 'Lugar');
  listapalavras.add(listPa223);
  PalavraForca listPa224 = new PalavraForca('Lanchonete', 'Lugar');
  listapalavras.add(listPa224);
  PalavraForca listPa225 = new PalavraForca('Batata Frita', 'Alimento');
  listapalavras.add(listPa225);
  PalavraForca listPa226 = new PalavraForca('Globo', 'Forma');
  listapalavras.add(listPa226);
  PalavraForca listPa227 = new PalavraForca('Academia', 'Lugar');
  listapalavras.add(listPa227);
  PalavraForca listPa228 = new PalavraForca('Fingimento', 'Mentira');
  listapalavras.add(listPa228);
  PalavraForca listPa229 = new PalavraForca('Dicionário', 'Livro');
  listapalavras.add(listPa229);
  PalavraForca listPa230 = new PalavraForca('Lista Telefônica', 'Livro');
  listapalavras.add(listPa230);
  PalavraForca listPa231 = new PalavraForca('Robô', 'Ficção Ciêntifica');
  listapalavras.add(listPa231);
  PalavraForca listPa232 = new PalavraForca('Híbrido', 'Criatura');
  listapalavras.add(listPa232);
  PalavraForca listPa233 = new PalavraForca('Lobisomem', 'Criatura');
  listapalavras.add(listPa233);
  PalavraForca listPa234 = new PalavraForca('Bruxa', 'Criatura');
  listapalavras.add(listPa234);
  PalavraForca listPa235 = new PalavraForca('Minotauro', 'Criatura');
  listapalavras.add(listPa235);
  PalavraForca listPa236 = new PalavraForca('Múmia', 'Criatura');
  listapalavras.add(listPa236);
  PalavraForca listPa237 = new PalavraForca('Loja', 'Comércio');
  listapalavras.add(listPa237);
  PalavraForca listPa238 = new PalavraForca('Dinheiro', 'Comércio');
  listapalavras.add(listPa238);
  PalavraForca listPa239 = new PalavraForca('Corporação', 'Comércio');
  listapalavras.add(listPa239);
  PalavraForca listPa240 = new PalavraForca('Gesto', 'Pessoa');
  listapalavras.add(listPa240);
  PalavraForca listPa241 = new PalavraForca('Mãe', 'Pessoa');
  listapalavras.add(listPa241);
  PalavraForca listPa242 = new PalavraForca('Pai', 'Pessoa');
  listapalavras.add(listPa242);
  PalavraForca listPa243 = new PalavraForca('Irmão', 'Pessoa');
  listapalavras.add(listPa243);
  PalavraForca listPa244 = new PalavraForca('Irmã', 'Pessoa');
  listapalavras.add(listPa244);
  PalavraForca listPa245 = new PalavraForca('Tio', 'Pessoa');
  listapalavras.add(listPa245);
  PalavraForca listPa246 = new PalavraForca('Tia', 'Pessoa');
  listapalavras.add(listPa246);
  PalavraForca listPa247 = new PalavraForca('Avó', 'Pessoa');
  listapalavras.add(listPa247);
  PalavraForca listPa248 = new PalavraForca('Avô', 'Pessoa');
  listapalavras.add(listPa248);
  PalavraForca listPa249 = new PalavraForca('Guaraná', 'Bebida');
  listapalavras.add(listPa249);
  PalavraForca listPa250 = new PalavraForca('Foice', 'Arma');
  listapalavras.add(listPa250);
  PalavraForca listPa251 = new PalavraForca('Brasileiro', 'Nascionalidade');
  listapalavras.add(listPa251);
  PalavraForca listPa252 = new PalavraForca('Nascionalidade', 'Caracteristica');
  listapalavras.add(listPa252);
  PalavraForca listPa253 = new PalavraForca('Espadachim', 'Pessoa');
  listapalavras.add(listPa253);
  PalavraForca listPa254 = new PalavraForca('Cavaleira', 'Pessoa Mulher');
  listapalavras.add(listPa254);
  PalavraForca listPa255 = new PalavraForca('Gladiadora', 'Pessoa Mulher');
  listapalavras.add(listPa255);
  PalavraForca listPa256 = new PalavraForca('Justiceira', 'Pessoa Mulher');
  listapalavras.add(listPa256);
  PalavraForca listPa257 = new PalavraForca('Arqueira', 'Pessoa Mulher');
  listapalavras.add(listPa257);
  PalavraForca listPa258 = new PalavraForca('Caçadora', 'Pessoa Mulher');
  listapalavras.add(listPa258);
  PalavraForca listPa259 = new PalavraForca('Guardiã', 'Pessoa Mulher');
  listapalavras.add(listPa259);
  PalavraForca listPa260 = new PalavraForca('Nova', 'Caracteristica');
  listapalavras.add(listPa260);
  PalavraForca listPa261 = new PalavraForca('Maga', 'Pessoa Mulher');
  listapalavras.add(listPa261);
  PalavraForca listPa262 = new PalavraForca('Alquimista', 'Misturas');
  listapalavras.add(listPa262);
  PalavraForca listPa263 = new PalavraForca('Feiticeira', 'Magia');
  listapalavras.add(listPa263);
  PalavraForca listPa264 = new PalavraForca('Arquimaga', 'Magia');
  listapalavras.add(listPa264);
  PalavraForca listPa265 = new PalavraForca('Ninja', 'Oriente');
  listapalavras.add(listPa265);
  PalavraForca listPa266 = new PalavraForca('Mercenário', 'Crime');
  listapalavras.add(listPa266);
  PalavraForca listPa267 = new PalavraForca('Vingador', 'Dar o troco');
  listapalavras.add(listPa267);
  PalavraForca listPa268 = new PalavraForca('Retaliador', 'Dar o troco');
  listapalavras.add(listPa268);
  PalavraForca listPa269 = new PalavraForca('Druida', 'Cultura');
  listapalavras.add(listPa269);
  PalavraForca listPa270 = new PalavraForca('Sentinela', 'Guarda');
  listapalavras.add(listPa270);
  PalavraForca listPa271 = new PalavraForca('Xamã', 'Indigênas');
  listapalavras.add(listPa271);
  PalavraForca listPa272 = new PalavraForca('Arcano', 'Magia');
  listapalavras.add(listPa272);
  PalavraForca listPa273 = new PalavraForca('Draconiano', 'Grand Chase');
  listapalavras.add(listPa273);
  PalavraForca listPa274 = new PalavraForca('Defensor', 'Protetor');
  listapalavras.add(listPa274);
  PalavraForca listPa275 = new PalavraForca('Inquisidor', 'Grand Chase');
  listapalavras.add(listPa275);
  PalavraForca listPa276 = new PalavraForca('Dançarina', 'Artista');
  listapalavras.add(listPa276);
  PalavraForca listPa277 = new PalavraForca('Musa', 'Inspiração');
  listapalavras.add(listPa277);
  PalavraForca listPa278 = new PalavraForca('Diva', 'Mulher famosa');
  listapalavras.add(listPa278);
  PalavraForca listPa279 = new PalavraForca('Superstar', 'Famoso(a)');
  listapalavras.add(listPa279);
  PalavraForca listPa280 = new PalavraForca('Lutador', 'Combate');
  listapalavras.add(listPa280);
  PalavraForca listPa281 = new PalavraForca('Mestre', 'Titulo');
  listapalavras.add(listPa281);
  PalavraForca listPa282 = new PalavraForca('Monge', 'Monásterio');
  listapalavras.add(listPa282);
  PalavraForca listPa283 = new PalavraForca('Iluminado', 'Stephen King');
  listapalavras.add(listPa283);
  PalavraForca listPa284 = new PalavraForca('Gladiador', 'Russel Crowe');
  listapalavras.add(listPa284);
  PalavraForca listPa285 = new PalavraForca('Comandante', 'Militar');
  listapalavras.add(listPa285);
  PalavraForca listPa286 = new PalavraForca('General', 'Militar');
  listapalavras.add(listPa286);
  PalavraForca listPa287 = new PalavraForca('Avatar', 'Dobrador');
  listapalavras.add(listPa287);
  PalavraForca listPa288 = new PalavraForca('Tecnomaga', 'Grand Chase');
  listapalavras.add(listPa288);
  PalavraForca listPa289 = new PalavraForca('Duelista', 'Grand Chase');
  listapalavras.add(listPa289);
  PalavraForca listPa290 = new PalavraForca('Polaris', 'Grand Chase');
  listapalavras.add(listPa290);
  PalavraForca listPa291 = new PalavraForca('La Geas', 'Grand Chase');
  listapalavras.add(listPa291);
  PalavraForca listPa292 = new PalavraForca('Profano', 'Grand Chase');
  listapalavras.add(listPa292);
  PalavraForca listPa294 = new PalavraForca('Drakar', 'Grand Chase');
  listapalavras.add(listPa294);
  PalavraForca listPa295 = new PalavraForca('Leviatã', 'Criatura');
  listapalavras.add(listPa295);
  PalavraForca listPa296 = new PalavraForca('Asmodeus', 'Criatura');
  listapalavras.add(listPa296);
  PalavraForca listPa297 = new PalavraForca('Andarilho', 'Viajante');
  listapalavras.add(listPa297);
  PalavraForca listPa298 = new PalavraForca('Errante', 'Mal intensionado');
  listapalavras.add(listPa298);
  PalavraForca listPa299 = new PalavraForca('Insurgente', 'Rebelde');
  listapalavras.add(listPa299);
  PalavraForca listPa300 = new PalavraForca('Invocadora', 'Magia');
  listapalavras.add(listPa300);
  PalavraForca listPa301 = new PalavraForca('Encantrix', 'Grand Chase');
  listapalavras.add(listPa301);
  PalavraForca listPa302 =
      new PalavraForca('Caçador de Recompensas', 'Profissão');
  listapalavras.add(listPa302);
  PalavraForca listPa303 = new PalavraForca('Rastreador', 'Profissão');
  listapalavras.add(listPa303);
  PalavraForca listPa304 = new PalavraForca('Justiceiro', 'Anti-Herói');
  listapalavras.add(listPa304);
  PalavraForca listPa305 = new PalavraForca('Especialista', 'Profissão');
  listapalavras.add(listPa305);
  PalavraForca listPa306 = new PalavraForca('Sacerdotisa', 'Ocupação');
  listapalavras.add(listPa306);
  PalavraForca listPa307 = new PalavraForca('Despertada', 'Caracteristica');
  listapalavras.add(listPa307);
  PalavraForca listPa308 = new PalavraForca('Caótica', 'Caracteristica');
  listapalavras.add(listPa308);
  PalavraForca listPa309 = new PalavraForca('Escolhida', 'Caracteristica');
  listapalavras.add(listPa309);
  PalavraForca listPa310 = new PalavraForca('Guerreiro', 'Caracteristica');
  listapalavras.add(listPa310);
  PalavraForca listPa311 = new PalavraForca('Ryujin', 'Oriente');
  listapalavras.add(listPa311);
  PalavraForca listPa312 = new PalavraForca('Paladina', 'Caracteristica');
  listapalavras.add(listPa312);
  PalavraForca listPa313 = new PalavraForca('Templária', 'Caracteristica');
  listapalavras.add(listPa313);
  PalavraForca listPa314 = new PalavraForca('Capitã', 'Militar');
  listapalavras.add(listPa314);
  PalavraForca listPa315 = new PalavraForca('Major', 'Militar');
  listapalavras.add(listPa315);
  PalavraForca listPa316 = new PalavraForca('Destruidor', 'Caos');
  listapalavras.add(listPa316);
  PalavraForca listPa317 = new PalavraForca('Sanguinário', 'Violento');
  listapalavras.add(listPa317);
  PalavraForca listPa318 = new PalavraForca('Dez', 'Numeral');
  listapalavras.add(listPa318);
  PalavraForca listPa319 = new PalavraForca('Fotografia', 'Imagem');
  listapalavras.add(listPa319);
  PalavraForca listPa320 = new PalavraForca('Gripe', 'Doença');
  listapalavras.add(listPa320);
  PalavraForca listPa321 = new PalavraForca('Pote', 'Objeto');
  listapalavras.add(listPa321);
  PalavraForca listPa322 = new PalavraForca('Epidemia', 'Saúde');
  listapalavras.add(listPa322);
  PalavraForca listPa323 = new PalavraForca('Tempestade', 'Clima');
  listapalavras.add(listPa323);
  PalavraForca listPa324 = new PalavraForca('Ciclope', 'Criatura');
  listapalavras.add(listPa324);
  PalavraForca listPa325 = new PalavraForca('Vontade', 'Querer algo');
  listapalavras.add(listPa325);
  PalavraForca listPa326 = new PalavraForca('Colegial', 'Da escola');
  listapalavras.add(listPa326);
  PalavraForca listPa327 =
      new PalavraForca('Dia Das Bruxas', 'Data comemorátiva');
  listapalavras.add(listPa327);
  PalavraForca listPa328 = new PalavraForca('Diversidade', 'Conceito');
  listapalavras.add(listPa328);
  PalavraForca listPa329 = new PalavraForca('Arsenal', 'Um coletivo');
  listapalavras.add(listPa329);
  PalavraForca listPa330 = new PalavraForca('Fóton', 'Física');
  listapalavras.add(listPa330);
  PalavraForca listPa331 = new PalavraForca('Escarlate', 'Cor');
  listapalavras.add(listPa331);
  PalavraForca listPa332 = new PalavraForca('Carruagem', 'Veiculo');
  listapalavras.add(listPa332);
  PalavraForca listPa333 = new PalavraForca('Xícara', 'Objeto');
  listapalavras.add(listPa333);
  PalavraForca listPa334 = new PalavraForca('Blusa De Frio', 'Tipo de roupa');
  listapalavras.add(listPa334);
  PalavraForca listPa335 = new PalavraForca('Sistema', 'Tecnologia');
  listapalavras.add(listPa335);
  PalavraForca listPa336 = new PalavraForca('Byte', 'Tecnologia');
  listapalavras.add(listPa336);
  PalavraForca listPa337 = new PalavraForca('Rio', 'Água');
  listapalavras.add(listPa337);
  PalavraForca listPa338 = new PalavraForca('Gelo', 'Água');
  listapalavras.add(listPa338);
  PalavraForca listPa339 = new PalavraForca('Folha', 'Vegetação');
  listapalavras.add(listPa339);
  PalavraForca listPa340 = new PalavraForca('Cacto', 'Vegetação');
  listapalavras.add(listPa340);
  PalavraForca listPa341 = new PalavraForca('Vegetação', 'Natureza');
  listapalavras.add(listPa341);
  PalavraForca listPa342 = new PalavraForca('Girassol', 'Vegetação');
  listapalavras.add(listPa342);
  PalavraForca listPa343 = new PalavraForca('Flor', 'Vegetação');
  listapalavras.add(listPa343);
  PalavraForca listPa344 = new PalavraForca('Árvore', 'Vegetação');
  listapalavras.add(listPa344);
}

void DefinirPalavrasCulturaPop() {
  PalavraForca p1 = new PalavraForca('Riverdale', 'Série de TV');
  listapalavras.add(p1);
  PalavraForca p2 = new PalavraForca('Eu nunca...', 'Série de TV');
  listapalavras.add(p2);
  PalavraForca p3 = new PalavraForca('Flash', 'DC Comics');
  listapalavras.add(p3);
  PalavraForca p4 = new PalavraForca('A Origem', 'Filme');
  listapalavras.add(p4);
  PalavraForca p5 = new PalavraForca('Lanterna Verde', 'DC Comics');
  listapalavras.add(p5);
  PalavraForca p6 = new PalavraForca('Os Vingadores', 'Marvel Comics');
  listapalavras.add(p6);
  PalavraForca p7 = new PalavraForca('Era uma vez em Hollywood', 'Filme');
  listapalavras.add(p7);
  PalavraForca p8 = new PalavraForca('Fundação', 'Livro');
  listapalavras.add(p8);
  PalavraForca p9 = new PalavraForca('Scooby Doo', 'Desenho');
  listapalavras.add(p9);
  PalavraForca p10 = new PalavraForca('Ben 10', 'Desenho');
  listapalavras.add(p10);
  PalavraForca p11 = new PalavraForca('Mulher Maravilha', 'DC Comics');
  listapalavras.add(p11);
  PalavraForca p12 = new PalavraForca('Stranger Things', 'Série de TV');
  listapalavras.add(p12);
  PalavraForca p13 = new PalavraForca('Xadrez', 'Jogo');
  listapalavras.add(p13);
  PalavraForca p14 = new PalavraForca('Battlefield', 'Jogo');
  listapalavras.add(p14);
  PalavraForca p15 = new PalavraForca('Mortal Kombat', 'Jogo');
  listapalavras.add(p15);
  PalavraForca p16 = new PalavraForca('Superman', 'DC Comics');
  listapalavras.add(p16);
  PalavraForca p17 = new PalavraForca('Drake e Josh', 'Série de TV');
  listapalavras.add(p17);
  PalavraForca p18 = new PalavraForca('Naruto', 'Anime/Manga');
  listapalavras.add(p18);
  PalavraForca p19 = new PalavraForca('Three Days Grace', 'Música');
  listapalavras.add(p19);
  PalavraForca p20 = new PalavraForca('Ted', 'Filme');
  listapalavras.add(p20);


}
